TRADUCTOR_EDITOR = [
    "traduccion",
    "edicion_literaria",
    "edicion",
    "direccion_de_edicion",
    "edicion_y_traduccion",
]

OTROS_CONTRIBUIDORES = [
    "epilogo",
    "prologo",
    "trabajo_preliminar",
    "contribucion",
    "introduccion",
    "comentarios_a_la_traduccion",
    "introduccion_a_notas",
    "prefacio",
    "notas",
    "compilacion",
]

ILUSTRACIONES = [
    "ilustracion",
    "ilustracion_fotografica",
    "fotografia",
]

ESCOLARES = [
    "material_enseñanza",
    "tipo_material_enseñanza",
    "tipo_enseñanza",
    "asignatura",
    "ciclo",
]

CATEGORIAS = [
    "categorias",
    "pais_de_publicacion",
    "asignatura",
    "tipo_material_enseñanza",
    "ciclo",
]

COLUMNAS_FINALES = [
    "isbn",
    "ean",
    "titulo",
    "editorial",
    "coleccion",
    "autoria",
    "traductor_y_editor",
    "otros_contribuidores",
    "aparato_critico",
    "tipo_aparato_critico",
    'categorias',
    "subcategorias",
    "idioma_original",
    "idioma_de_publicacion",
    "fecha_publicacion",
    "n_paginas",
    "precio",
    "alto_mm",
    "ancho_mm",
    "grueso",
    "peso",
    "encuadernacion",
    "es_escolar",
    "es_ilustrado",
    "es_ibd",
    "sinopsis",
    "url",
    "img",
]


CATEGORIAS_SPI = [
    "Antropología",
    "Arqueología", 
    "Bellas Artes",
    "Biblioteconomía",
    "Comunicación",
    "Derecho",
    "Economía",
    "Educación",
    "Filosofía",
    "Geografía",
    "Historia",
    "Literatura",
    "Política",
    "Psicología",
    "Sociología"
]



SUBCATEGORIAS = {
    'Antropología': [
        'Sociología y antropología',
        'Antropología social y cultural, etnografía',
        'Antropología evolutiva / Evolución humana',
        'Antropología evolutiva / evolución humana',
        'Cuestiones y debates éticos',
        'Estudios culturales',
        'Estudios sobre el folclore / estudios sobre mitos (mitología)'
    ],
    'Arqueología': [
        'Historia y arqueología',
        'Arqueología',
        'Yacimientos arqueológicos',
        'Paleontología'
    ],
    'Bellas Artes': [
        'Música',
        'Ópera',
        'Arquitectura',
        'Artes',
        'Arte musical, música orquestal y académica',
        'Otras formas de arte gráfico o visual',
        'Películas, cine',
        'Escultura',
        'Artes escénicas',
        'Fotografía y fotógrafos',
        'Biografía: arte y espectáculo',
        'Pintura, técnica de pintura',
        'Historia del arte',
        'Figuras humanas representadas en el arte',
        'Música popular',
        'Artes: aspectos generales',
        'Artistas, monografías sobre arte',
        'Música sacra y religiosa',
        'Fotografía: retratos y autorretratos',
        'Moda y diseño de tejidos',
        'Teoría del arte',
        'Historia, teoría y crítica cinematográfica',
        'Infantil/Juvenil, interés general: música y músicos',
        'Libros y «packs» infantiles interactivos y de actividades: dibujar, colorear y pintar',
        'Infantil/Juvenil, interés general: artesanías',
        'Músicas del mundo y estilos regionales',
        'Música tradicional y folclórica',
        'Fotografías: colecciones',
        'Infantil/Juvenil, interés general: artes y artistas',
        'Infantil/Juvenil, interés general: danza, «ballet»',
        'Dibujo y dibujos',
        'Cine: estilos y géneros',
        'Artesanías, artes decorativas y manualidades',
        'Artes decorativas',
        'Desnudos representados en el arte',
        'Conservación, restauración y cuidado de obras de arte',
        'Fotografía: técnicas y principios específicos',
        'Diseño gráfico',
        'Directores de cine, productores',
        'Arte religioso y ceremonial',
        'Diseño de muebles',
        'Guías y revistas de cine',
        'Sectores del cine, la radio y la televisión',
        'Música electrónica',
        'Música coral',
        'Urbanismo y urbanización: aspectos arquitectónicos',
        'Retratos y autorretratos en el arte',
        'Artes: técnicas y principios artísticos',
        'Diseñadores individuales o grupos de diseño',
        'Libros de cocina y restaurantes de cocineros famosos y de televisión',
        'Ballet',
        'Industria de la música',
        'Cómics, viñetas y dibujos animados',
        'Diseño de libros',
        'Música de cine y espectáculos',
        'Dirección y producción de teatro',
        'Gestión de teatros',
        'Teatro: técnicas y competencias básicas',
        'Los animales en el arte',
        'Realización y producción cinematográfica: conocimientos básicos y técnicos',
        'Adulteración, falsificación y sustracción de obras de arte',
        'Oficios, técnicas y artes tradicionales',
        'Terapia creativa (por ejemplo, arte, música, teatro)',
        'Sciences in medicine and healthcare',
        'Cerámica, mosaicos y vidrio: obras de arte',
        'Obras de arte textil',
        'Internet y medios digitales: arte y actuación',
        'Formas de arte no gráfico o digital',
        'Arte: aspectos económicos',
        'La naturaleza en el arte',
        'Arte de la «performance»',
        'Manuales de pintura, dibujo y arte',
        'Arte digital, de los nuevos medios y videoarte',
        'Grabados y estampación',
        'Arquitectura: castillos y fortificaciones',
        'Arquitectura: palacios, casas solariegas, mansiones',
        'Enseñanza: música',
        'Enseñanza: arte y diseño',
        'Tecnología de los tintes, pigmentos y pinturas',
        'Arte público',
        'Fotoperiodismo y fotografía documental',
        'Guiones y guionistas de cine',
        'Ilustración y arte comercial',
        'Diseño de productos',
        'Géneros de cine, televisión o radio: histórico',
        'Arquitectura y diseño respetuosos con el medioambiente («verde»)',
        'Arquitectura: edificaciones domésticas de pequeñas dimensiones',
        'Géneros de cine, televisión o radio: comedia y humor',
        'Cine, televisión, radio y artes escénicas',
        'Géneros de cine, televisión o radio: ciencia ficción, fantasía y terror',
        'Géneros de cine, televisión o radio: drama',
        'Equipos y técnicas de fotografía en general',
        'Arte erótico',
        'Metales preciosos, piedras preciosas y alhajas: obras de arte y diseño',
        'Arte y pinturas murales',
        'Guías de diseño de interiores, decoración y estilo',
        'Arte botánico',
        'Artes marciales',
        'Diseño y planificación de jardines',
        'Antigüedades, objetos de época y coleccionables: fotografías, grabados y mapas',
        'Cine, televisión, radio y artes escénicas: obras de acompañamiento',
        'Escenas de arte a pequeña escala seculares y domésticas',
        'Enseñanza: teatro y artes escénicas',
        'Infantil/Juvenil, interés general: dibujos animados y tebeos',
        'Ficción infantil / Ficción juvenil: ópera espacial («space opera»)',
        'Materiales en la arquitectura',
        'Acuarela o pastel: obras y técnica',
        'Antigüedades, objetos de época y coleccionables: joyas',
        'Cancioneros',
        'Catálogos de exposiciones y colecciones específicas',
        'Fotógrafos individuales',
        'Ilustración',
        'Instalaciones artísticas',
        'Instrumentos de teclado',
        'Manualidades con libros y papel',
        'Técnicas de actuación'
    ],
    'Biblioteconomía': [
        'Bibliografías, catálogos',
        'Bibliotecas y ciencias de la información/Museología',
        'Bibliotecas y ciencias de la información/museología',
        'Infantil / juvenil, material de consulta: diccionarios y material de referencia',
        'Infantil/jugenil, interés general: fuentes de información',
        'Investigación e información: general',
        'Paleografía',
        'Publicaciones por entregas, periódicos, resúmenes, índices'
    ],
    'Comunicación': [
        'Lingüística e idiomas',
        'Diccionarios',
        'Reportajes, periodismo o colecciones de artículos periodísticos',
        'Lingüística histórica y comparada',
        'Infantil/Jugeníl, interés general: televisión, vídeo y películas',
        'Industria editorial y periodismo',
        'Guías de redacción y corrección de textos',
        'Comunicación y presentación empresarial',
        'Humor relacionado con los medios de comunicación',
        'Infantil/juvenil, cuestiones personales y sociales: drogas y adicciones',
        'Diccionarios biográficos',
        'Estudios de comunicación',
        'Ingeniería de las comunicaciones/las telecomunicaciones',
        'Adicciones y su tratamiento',
        'Radio/pódcast',
        'Bilingüismo y plurilingüismo',
        'Publicidad',
        'Televisión',
        'Sociolingüística',
        'Redes y comunicaciones informáticas',
        'Diccionarios temáticos',
        'Narrativa romántica: ricos, famosos, poderosos',
        'Comunicación interpersonal y habilidades sociales',
        'Hacer frente / asesorarse sobre las adicciones',
        'Programación neurolingüística (PNL)',
        'Televisión: estilos y géneros',
        'Poderes psíquicos y fenómenos psíquicos',
        'Gramática, sintaxis y morfología',
        'Tesauros / Diccionarios de sinónimos',
        'Diccionarios bilingües y multilingües',
        'Semiótica/semiología',
        'Guiones, obras e interpretaciones radiofónicos',
        'Aprendizaje de idiomas: gramática, vocabulario y pronunciación',
        'Lingüística computacional y de corpus',
        'Conocimientos jurídicos: elaboración y redacción de textos jurídicos',
        'Infantil / Juvenil, material de consulta: diccionarios y material de referencia',
        'Aprendizaje de lenguas: destrezas de expresión oral/pronunciación',
        'Dialecto, argot y jerga',
        'Estudios sobre medios',
        'Guías gramaticales y de uso',
        'Guiones obras y representaciones televisivas',
        'Lexicografía',
        'Películas documentales',
        'Producción televisiva: conocimientos básicos y técnicos',
        'Relaciones públicas',
        'Semántica, análisis del discurso, etc.',
        'Tecnología de la telefonía',
        'Textos de autoestudio de lenguas extranjeras',
        'Traducción e interpretación',
        'Fonética, fonología'
    ],
    'Derecho': [
        'Derecho del deporte',
        'Derecho penal: delitos contra la persona',
        'Derecho de los animales',
        'Derechos civiles y ciudadanía',
        'Derecho constitucional y administrativo',
        'Derecho privado o civil: generalidades',
        'Derecho y procedimiento penal',
        'Derecho',
        'Metodología, teoría y filosofía del derecho',
        'Derecho: derechos humanos y libertades civiles',
        'Derecho del trabajo',
        'Derecho internacional marítimo',
        'Derecho internacional público: Espacios marinos y Derecho del mar',
        'Derecho mercantil',
        'Derecho comparado',
        'Derecho de familia',
        'Fuentes de derecho: legislación',
        'Constitución: Gobierno y Estado',
        'Derechos humanos, derechos civiles',
        'Historia del derecho',
        'Constitución',
        'Derecho tributario y arancelario',
        'Derecho inmobiliario / Derecho real, bienes inmuebles',
        'Adivinación mediante atributos físicos',
        'Derecho Internacional público: Derecho Económico Internacional e integración',
        'Derecho internacional público: Derecho Humanitario e intervención',
        'Ordenamientos jurídicos: procesos civiles, litigios y resolución de conflictos',
        'Contratación mercantil. Obligaciones y contratos',
        'Derecho internacional público: derechos humanos',
        'Derecho mercantil, de sociedades y de la competencia',
        'Derecho romano',
        'Ordenamientos jurídicos: general',
        'Derecho y sociedad: cuestiones relativas al género',
        'Derecho y sociedad: sociología del derecho',
        'Derecho de la libertad de información',
        'Proceso penal',
        'Derecho bursátil. Derecho de los mercados de capitales',
        'Derecho energético y de los recursos naturales',
        'Derecho internacional público: Derecho penal',
        'Derecho penal de menores',
        'Derecho de la justicia penal',
        'Derecho de la seguridad social y servicios asistenciales',
        'Derecho sanitario y de la seguridad pública',
        'Derecho médico y sanitario',
        'Derecho mercantil. Derecho financiero',
        'Profesión jurídica / práctica del derecho: general',
        'Ley islámica (Shariah)',
        'Derecho: guías de estudio y revisión',
        'Derecho de bienes. Derecho de propiedad',
        'Derecho sobre bienes personales',
        'Fuentes del derecho: jurisprudencia, precedentes',
        'Derecho de las personas mayores.',
        'Constitución: gobierno y estado',
        'Contratación mercantil. obligaciones y contratos'
    ],
    'Economía': [
        'Economía y empresa',
        'Historia de la economía',
        'Negocios internacionales',
        'Banca',
        'Economía popular',
        'Economía internacional',
        'Economía agrícola y rural',
        'Economía regional / urbana',
        'Empresa y gestión',
        'Finanzas y sector financiero',
        'Economía política',
        'Contabilidad',
        'Microeconomía',
        'Propiedad y organización de empresas',
        'Empresas en manos de los trabajadores y cooperativas',
        'Economía del trabajo y la retribución',
        'Economía del bienestar',
        'Finanzas personales',
        'Economía del desarrollo y economías emergentes',
        'Emprendimiento y emprendedores / empresas emergentes / «startups»',
        'Estrategia empresarial',
        'Economía monetaria',
        'Ventas y marketing',
        'Economía de sectores específicos',
        'Macroeconomía',
        'Toma de decisiones en la gestión de empresas',
        'Innovación empresarial',
        'Biografía: negocios e industria',
        'Economía digital o de internet',
        'Enseñanza: estudios empresariales y economía',
        'Negociación empresarial',
        'Pequeñas empresas y trabajadores autónomos',
        'Contabilidad de gestión, teneduría de libros y auditoría',
        'Ética empresarial y responsabilidad social',
        'Economía conductista/conductual',
        'Delincuencia empresarial y de guante blanco',
        'Estudios empresariales: general',
        'Economía medioambiental',
        'Economía de la salud',
        'Banca y finanzas: guías de estudio y revisión',
        'Aprendizaje de idiomas para negocios, actividades profesionales y formación profesional',
        'Historia de empresas específicas/historia societaria',
        'Competencia empresarial',
        'Acuicultura y piscicultura',
        'Agricultura y ganadería',
        'Agricultura, agroindustria e industrias de producción de alimentos',
        'Agronomía y producción agrícola',
        'Capitalismo',
        'Comercio internacional',
        'Consejos sobre carreras profesionales y cómo alcanzar el éxito',
        'Crisis y desastres económicos y financieros',
        'Formación profesional, industrial o vocacional',
        'Gestión de áreas específicas',
        'Gestión de oficina',
        'Gestión de proyectos',
        'Gestión: liderazgo y motivación',
        'Hacienda pública, fiscalidad',
        'Horticultura comercial',
        'Industria de los ordenadores y videojuegos',
        'Industria pecuaria',
        'Industria y estudios industriales',
        'Industrias de la hostelería, el deporte, el ocio y el turismo',
        'Industrias de la tecnología de la información',
        'Industrias de los ordenadores y videojuegos',
        'Industrias extractivas',
        'Inversiones y títulos valores',
        'Investigación de mercado',
        'Multinacionales',
        'Propiedad y bienes raíces',
        'Sectores de la moda y belleza',
        'Seguros y estudios actuariales',
        'Sistemas y equipamientos de oficina',
        'Sistemas y estructuras económicas',
        'Teoría y comportamiento organizativos'
    ],
    'Educación': [
        'Infantil y juvenil',
        'Educación multidisciplinar y cultura general',
        'Educación',
        'Libros de texto, manuales y material educativo',
        'Tradiciones filosóficas y escuelas de pensamiento',
        'Ficción infantil / Ficción juvenil: relatos sobre la escuela',
        'Enseñanza: matemáticas y cálculo',
        'Enseñanza: lengua materna/nativa',
        'Enseñanza: lengua, literatura y alfabetización',
        'Enseñanza: matemáticas, ciencia y tecnología, general',
        'Enseñanza: cuadernos de vacaciones',
        'Enseñanza: ciencias, general',
        'Enseñanza: tecnología',
        'Enseñanza: ciencias sociales, estudios sociales',
        'Enseñanza: estudios de religión',
        'Enseñanza y aprendizaje de lenguas',
        'Enseñanza: lenguas modernas (no maternas/nativas o segundas)',
        'Infantil / Juvenil, cuestiones personales y sociales: escuela, educación y profesores',
        'Salud personal y pública/educación para la salud',
        'Escuelas secundarias',
        'Escuelas primarias e intermedias',
        'Enseñanza de alumnos con discapacidades físicas',
        'Recursos y materiales didácticos para docentes',
        'Cuerpo docente / de educadores',
        'Sistemas de escritura, alfabetos',
        'Finalidad moral y social de la educación',
        'Enseñanza a estudiantes con dificultades de aprendizaje',
        'Consejos sobre la educación',
        'Infantil / Juvenil, cuestiones personales y sociales: educación sexual y realidades de la vida',
        'Educación/pedagogía progresista',
        'Enseñanza: ciencias de la familia y el consumidor/gestión doméstica',
        'Formación docente',
        'Enseñanza: historia',
        'Enseñanza: geografía',
        'Alfabetismo',
        'Enseñanza: otros tipos de formación profesional',
        'Enseñanza: educación física',
        'Enseñanza: estudios generales, destrezas y competencias educativas',
        'Enseñanza: formación profesional y otros temas',
        'Enseñanza a estudiantes con dificultades sociales, emocionales o conductuales',
        'Enseñanza: filosofía y ética',
        'Primeros años: el abecedario / el alfabeto',
        'Ciencia del deporte, educación física',
        'Autismo y síndrome de asperger',
        'Infantil / juvenil, cuestiones personales y sociales: escuela, educación y profesores',
        'Infantil / juvenil, cuestiones personales y sociales: educación sexual y realidades de la vida',
        'Infantil / juvenil, cuestiones personales y sociales: orientación profesional, final de la escolaridad y continuación de los estudios',
        'Libro del alumno',
        'Preescolar y jardín de infancia',
        'Primeros años / conceptos de aprendizaje temprano',
        'Tutorización y atención al estudiante'
    ],
    'Filosofía': [
        'Filosofía popular',
        'Filosofía ética y moral',
        'Filosofía social y política',
        'Filosofía popular: el sentido de la vida / encontrar el sentido a la vida',
        'Filosofía occidental desde 1800, aproximadamente',
        'Filosofía y religión',
        'Filosofía antigua griega y romana',
        'Biografía: filosofía y ciencias sociales',
        'Filosofía: metafísica y ontología',
        'Teoría y filosofía económicas',
        'Filosofía de la religión',
        'Filosofía: estética',
        'Filosofía: epistemología y teoría del conocimiento',
        'Filosofía occidental: Ilustración',
        'Infantil/Juvenil, interés general: criaturas sobrenaturales y mitológicas',
        'Ficción metafísica / filosófica',
        'Infantil/Juvenil, interés general: filosofía, religión y creencias',
        'Filosofía: lógica',
        'Filosofía de la ciencia',
        'Filosofía de la mente',
        'Medicina musculoesquelética',
        'Genética (no médica)',
        'Filosofía islámica y árabe',
        'Cibernética y teoría de sistemas',
        'La filosofía occidental en la Edad Media',
        'Bioética',
        'Lógica matemática',
        'Filosofía de Asia y de la India',
        'Ingeniería genética',
        'Filosofía del lenguaje',
        'Salud y seguridad en el puesto de trabajo',
        'Industrias químicas, biotecnológicas y farmacéuticas',
        'Filosofía humanista',
        'Temas de la filosofía',
        'Ética médica y conducta profesional',
        'Baloncesto',
        'Adivinación por medio de la interpretación de las cartas (cartomancia)',
        'Alternativas humanistas y seculares a la religión',
        'Aspectos de la religión',
        'Astrología',
        'Budismo',
        'Budismo: ramas y grupos',
        'Clarividencia y precognición',
        'Cristianismo',
        'Cristianismo: textos y escritos sagrados',
        'Crítica y exégesis de textos sagrados',
        'Cuestiones y debates religiosos',
        'El más allá, reencarnación y vidas pasadas',
        'Espíritus guía, ángeles y canalización',
        'Espiritualidad y experiencia religiosa',
        'Fenómenos inexplicables/paranormales',
        'Filosofía de asia y de la india',
        'Filosofía occidental: ilustración',
        'Hinduismo',
        'I ching',
        'Iglesias cristianas, confesiones, denominaciones, grupos',
        'Infantil/juvenil, interés general: budismo',
        'Infantil/juvenil, interés general: cristianismo',
        'Infantil/juvenil, interés general: filosofía, religión y creencias',
        'Instituciones y organizaciones religiosas',
        'Islam',
        'Judaísmo',
        'La filosofía occidental en la edad media',
        'Magia, encantamientos y alquimia',
        'Mindfulness. atención o conciencia plena',
        'Misticismo, magia y rituales',
        'Ocultismo',
        'Oraciones y material litúrgico',
        'Otras religiones y creencias',
        'Ovnis y seres extraterrestres',
        'Pensamiento e ideología ecologista',
        'Religión comparada',
        'Religión y mitología celtas',
        'Religión y mitología de la antigua grecia',
        'Religión y mitología del antiguo egipto',
        'Religión y mitología nórdicas',
        'Religión y mitología romana',
        'Religión: generalidades',
        'Religiones de asia oriental',
        'Religiones y mitologías antiguas',
        'Religiones y sistemas de creencias eclécticas y esotéricas',
        'Teología',
        'Textos antiguos, clásicos y medievales',
        'Textos y escritos sagrados del budismo',
        'Textos y escritos sagrados del hinduismo',
        'Textos y escritos sagrados del islam',
        'Vida y práctica budistas',
        'Vida y práctica cristianas',
        'Vida y práctica hinduistas',
        'Vida y práctica religiosa'
    ],
    'Geografía': [
        'Comunidades rurales',
        'Ficción urbana',
        'Ficción infantil / Ficción juvenil: fantasía urbana contemporánea',
        'Atlas o mapas del mundo / regionales',
        'Mapas geográficos: especializados / temáticos',
        'Geografía humana',
        'Geografía regional',
        'Planificación y gestión urbana y municipal',
        'Geografía histórica',
        'Fantasía urbana',
        'Geografía de los asentamientos urbanos y rurales',
        'Comunidades urbanas',
        'Novela romántica: wésterns, rurales o campestres («outback»)',
        'Infantil/Juvenil, interés general: vida urbana',
        'Geografía del turismo',
        'Geografía política',
        'Cartografía, elaboración de mapas y proyecciones',
        'Cartas celestes y atlas astronómicos',
        'Geografía económica',
        'Mapas y atlas de viaje',
        'Subject atlases / Visual reference',
        'Geografía: obras de referencia',
        'Planificación y gestión rural',
        'Geografía del desarrollo y del medio ambiente',
        'Geografía física y topografía',
        'Cultivos urbanos/agricultura urbana',
        'Mapas de calles y planos de ciudades',
        'Mapas de viaje',
        'Atlas y mapas de carreteras',
        'Infantil / Juvenil, material de consulta: atlas y mapas',
        'Infantil/Juvenil, interés general: vida rural',
        'Argentina',
        'Colombia',
        'Consejos prácticos para viajar: general',
        'Descubrimiento y exploración geográficas',
        'España',
        'Expediciones: narraciones populares',
        'Guías de viaje y turismo',
        'Guías de viaje: restaurantes, cafeterías y bares',
        'Guías de viaje: vacaciones de aventura',
        'Infantil/juvenil, interés general: exploración y descubrimiento',
        'Infantil/juvenil, interés general: países, cultura e identidad nacional',
        'Infantil/juvenil, interés general: personas y lugares',
        'Libros de frases para el viajero',
        'Lugares y personas: obras generales y pictóricas',
        'México',
        'Montañas y tierras altas',
        'Oceanografía (mares y océanos)',
        'Portugal',
        'Procesos geológicos de la superficie de la tierra (geomorfología)'
    ],
    'Historia': [
        'Literatura: historia y crítica',
        'Cuentos, Historias cortas',
        'Historias marítimas',
        'Historia general y del mundo',
        'Historia social y cultural',
        'Historia de Europa',
        'Ficción: historias tradicionales, mitos y cuentos de hadas',
        'Historia de Asia',
        'Historia: acontecimientos y temas específicos',
        'Historias reales de guerra y combate',
        'Historia de Europa: Renacimiento',
        'Historia de la ciencia',
        'Historia marítima',
        'Historia militar',
        'Historia Antigua',
        'Jardines (descripciones, historia, etc.)',
        'Historia: teoría y métodos',
        'Historia de la religión',
        'Historias reales: general',
        'Historia de la medicina',
        'Ficción infantil / Ficción juvenil: historias de relaciones: relatos románticos, de amor o de amistad',
        'Ficción infantil / Ficción juvenil: terror, historias de fantasmas y de miedo',
        'Ficción infantil / Ficción juvenil: historias inspiradas en medios ajenos al libro o adaptadas a partir de ellos',
        'Ficción infantil / Ficción juvenil: historias de amistad',
        'Ficción infantil / Ficción juvenil: romances e historias de amor',
        'Ficción infantil / Ficción juvenil: aventuras e historias interactivas',
        'Infantil/Juvenil, interés general: historia y el pasado',
        'Historia del conocimiento (fundamentalmente para ciencias sociales y humanidades)',
        'Historias reales de supervivencia en abusos o injusticias',
        'Ficción infantil / Ficción juvenil: historias en verso',
        'Ficción infantil / Ficción juvenil: historias reales contadas como ficticias',
        'Ficción infantil / Ficción juvenil: ficción biográfica / historias autobiográficas',
        'Historia de América',
        'Novela gráfica, cómics o manga: memorias, historias reales y no ficción',
        'Terror contemporáneo e historias de fantasmas',
        'Historia de otras zonas y regiones geográficas',
        'Historiografía',
        'Lengua: historia y obras generales',
        'Historia de las matemáticas',
        'Historia de África',
        'Historia de Oriente Próximo',
        'Historia de Europa: Edad Media',
        'Historias reales de heroísmo, resistencia y supervivencia',
        'Confesiones e historias reales eróticas',
        'Historia de Australasia y del Pacífico',
        'Historia de la tecnología y la ingeniería',
        'Historia de Europa: romanos',
        'Historia de Europa: Reforma',
        'La Tierra: historia natural general. Interés general',
        'Ciencia ficción: historias de aventuras en el espacio',
        'Historia local',
        'Historia de Europa: vikingos',
        'Historia de América: período precolombino',
        'Historia del deporte',
        'Historias de superhéroes',
        'Historia familiar, genealogía',
        'Historia oral',
        'Historia de la industria y la industrialización',
        'Historias reales sobre descubrimientos, historia o ciencia',
        'Historia de África. período precolonial',
        'Historia: plagas, enfermedades, hambrunas, etc.',
        'Historias de vida animal',
        'Infantil/Juvenil, interés general: historias extraídas de textos sagrados o traditions religiosas',
        'Ficción infantil / Ficción juvenil: historias del calendario de Adviento',
        'Colonialismo e imperialismo',
        'Conflicto armado',
        'Diarios, correspondencia',
        'Enigmas, delitos y crímenes históricos',
        'Esclavitud y abolición de la esclavitud',
        'Fuerzas guerrilleras o irregulares y guerra',
        'Genealogía, heráldica, nombres y honores',
        'Genocidio y limpieza étnica',
        'Guerra en la antigüedad',
        'Guerra moderna',
        'Guerra y defensa',
        'Guerras frías y conflictos subsidiarios («proxy conflicts»)',
        'Guerras y campañas específicas',
        'Historia antigua',
        'Historia de américa',
        'Historia de asia',
        'Historia de europa',
        'Historia de europa: edad media',
        'Historia de europa: reforma',
        'Historia de europa: romanos',
        'Historia de oriente próximo',
        'Historia de áfrica',
        'Historia de áfrica. período precolonial',
        'Infantil/juvenil, interés general: historia y el pasado',
        'Infantil/juvenil, interés general: material bélico, batallas y guerras, ejércitos',
        'Inteligencia militar',
        'Investigación histórica: fuentes documentales',
        'La guerra en los comienzos de la edad moderna (incluyendo el uso de la pólvora)',
        'Liberación nacional e independencia',
        'Revoluciones, levantamientos y rebeliones',
        'Sagas islandesas y nórdicas antiguas'
    ],
    'Literatura': [
        'Ficción moderna y contemporánea: general y literaria',
        'Biografía: escritores',
        'Ficción humorística',
        'Thriller/suspense',
        'Ficción especulativa',
        'Ficción',
        'Novelas sobre estilos de vida contemporáneos',
        'Literatura de viajes',
        'Biografía: general',
        'Novelas sobre la vida familiar',
        'Autobiografía: general',
        'Memorias',
        'Poesía',
        'Ficción biográfica / ficción autobiográfica',
        'Ficción: inspirada o adaptado a partir de soportes que no sean libros',
        'Biografías y estudios literarios',
        'Ficción histórica',
        'Fantasía',
        'Ficción clásica: general y literaria',
        'Colección de biografías',
        'Mitos y leyendas / Ficción mítica',
        'Ficción de terror y lo sobrenatural',
        'Fantasía romántica',
        'Biografía: ciencia, tecnología y medicina',
        'Novelas de sagas familiares/generacionales',
        'Fantasía contemporánea',
        'Ficción sobre distopías y utopías',
        'Ficción basada o inspirada en hechos reales',
        'Biografía: histórica, política y militar',
        'Literatura clásica de viajes',
        'Biografía: religiosa y espiritual',
        'Novelas de aventuras militares, de guerra y de combate',
        'Novelas clásicas policiacas y de misterio',
        'Ficción infantil / Ficción juvenil: fantasía negra («dark fantasy»)',
        'Ficción infantil / Ficción juvenil: fantasía romántica',
        'Ficción infantil/juvenil: relatos de humor',
        'Ficción infantil / Ficción juvenil: ficción de crimen y misterio',
        'Ficción infantil / Ficción juvenil: thrillers/suspense',
        'Ficción infantil / Ficción juvenil: fantasía',
        'Ficción infantil / Ficción juvenil: relatos de acción y aventuras',
        'Novela gráfica, cómic o manga: vida escolar o universitaria',
        'Ficción infantil / Ficción juvenil: realismo mágico, fantasía mágica',
        'Ficción infantil / Ficción juvenil: ficción clásica',
        'Ficción infantil / Ficción juvenil: general, moderna y contemporánea',
        'Ficción infantil / Ficción juvenil: ficción especulativa, distópica y utópica',
        'Ficción erótica',
        'Narrativa romántica oscura («dark romance»)',
        'Ficción infantil / Ficción juvenil: relatos sobre animales y naturaleza',
        'Ficción infantil / Ficción juvenil: relatos sobre la familia y el hogar',
        'Ficción satírica y paródica',
        'Crimen y misterio: novela negra',
        'Ficción infantil / Ficción juvenil: cuentos tradicionales',
        'Infantil/Juvenil, interés general: biografías y autobiografías',
        'Thriller/suspense: asesinos en serie',
        'Ficción infantil / Ficción juvenil: fantasía épica / fantasía heroica',
        'Ficción infantil/juvenil: relatos sobre deportes',
        'Ciencia ficción',
        'Ficción de género',
        'Ficción infantil / Ficción juvenil: ciencia ficción',
        'Ficción de aventuras/acción',
        'Novela histórica alternativa',
        'Suspense médico / Thriller médico',
        'Thriller psicológico',
        'Aventuras de ficción: Westerns',
        'Novela gráfica, cómic o manga: acción y aventura',
        'Thriller sobre asuntos políticos y legales',
        'Fantasía épica/fantasía heroica',
        'Biografía: deporte',
        'Libros ilustrados de cuentos',
        'Ciencia ficción: Militar',
        '«Technothriller», tecnosuspense',
        'Ficción religiosa y espiritual',
        'Infantil/Juvenil, interés general: literatura, libros y escritores',
        'Fantasía histórica',
        'Ficción infantil / Ficción juvenil: cuentos, relatos cortos',
        'Ciencia ficción: alienígenas/ovnis',
        'Ciencia ficción clásica',
        'Novela gráfica, cómic o manga: humorística',
        'Thriller sobre espías y espionaje',
        'Ficción deportiva',
        'Ficción traducida',
        'Infantil/Juvenil: poesía',
        'Ficción infantil / Ficción juvenil: ficción histórica',
        'Ficción infantil / Ficción juvenil: ejércitos y guerra',
        'Novela gráfica, cómic o manga: fantasía, esoterismo',
        'Novela gráfica, cómic o manga: romántica',
        'Ciencia ficción: viajes en el tiempo',
        'Ficción infantil / Ficción juvenil: fantasía histórica',
        'Ficción infantil / Ficción juvenil: «steampunk»',
        'Infantil / Juvenil, cuestiones personales y sociales: contactos, noviazgo, relaciones, romances y amor',
        'Ficción infantil / Ficción juvenil: fantasía mítica / ficción mítica',
        'Biografía: aventureros y exploradores',
        'Novela gráfica, cómic o manga: horror, sobrenatural',
        'Cómics de estilo o tradición estadouinidenses',
        'Novela gráfica, cómics o manga: adaptaciones literarias',
        'Cómics de tradición o estilo europeos',
        'Tiras de cómics',
        'Parodias y chanzas/bromas: no ficción',
        'Cuentos clásicos de terror y fantasmas',
        'Biografía: realeza',
        'Manuales de literatura, reseñas y guías de libros',
        'Fantasía cómica (humorística)',
        'Cómic y manga',
        'Novelas gráficas',
        'Literatura griega y romana antiguas',
        'Fantasía negra («dark fantasy»)',
        'Ficción epistolar',
        'Ciencia ficción: apocalíptica y posapocalíptica',
        'Ciencia ficción: futuro cercano',
        'Ciencia ficción: exploración espacial',
        'Thriller esotérico',
        'Romance: love triangles',
        'Romance: unlikely or unexpected lovers',
        'Romance: enemies to lovers',
        'Romance: cosy / cozy',
        'Romance: friends to lovers',
        'Romance: unintentional or forced proximity',
        'Romance: sports',
        'Romance: workplace',
        'Romance: fake or pretend relationships',
        'Narrativa romántica: fantasía y paranormal',
        'Suspense / Thriller: crimen organizado',
        'Romance: college / university',
        'Ficción infantil / Ficción juvenil: novela por entregas (folletines)',
        'Romance: bad boys / bad girls',
        'Cuentos populares y de hadas / Recreación de cuentos de hadas',
        'Ficción de lo oculto (ocultismo)',
        'Ciencia ficción: «steampunk»',
        'Novela corta',
        'Fantasmas y poltergeist',
        'Cómics de estilo manga o de tradición asiática oriental',
        'Novela gráfica, cómic o manga: superhéroes y supervillanos',
        'Novela gráfica, cómic o manga: ciencia ficción',
        'Novela gráfica, cómic o manga: crimen, misterio y suspense',
        'Cómics de estilo o tradición europeos',
        'Novela gráfica, cómic o manga: histórica',
        'Novela gráfica, cómic o manga: ficción o literatura modernas y contemporáneas',
        'Ficción: pastiche',
        'Novela gráfica / cómic: para adultos',
        'Biografía: medios sociales',
        'Formas de poesía: soneto',
        'Financial / Corporate thrillers',
        'Thriller/suspense: terrorismo',
        'Antologías: general',
        'Aventura histórica',
        'Aventuras de ficción: westerns',
        'Colecciones y antologías de humor',
        'Comedias',
        'Creación literaria y guías de creación literaria',
        'Crimen y misterio en clave humorística',
        'Crimen y misterio: misterio «amable» («cosy mystery»)',
        'Crimen y misterio: mujeres detectives',
        'Crimen, delito y misterio: detectives privados/detectives aficionados',
        'Crimen, delito y misterio: procedimientos policiales',
        'Cuentos populares y de hadas / recreación de cuentos de hadas',
        'Discursos',
        'Ensayos literarios',
        'Espionaje y servicios secretos',
        'Estudios literarios: antiguos, clásicos y medievales',
        'Estudios literarios: c. 1500-c. 1800',
        'Estudios literarios: c. 1800-c. 1900',
        'Estudios literarios: c. 1900-c. 2000',
        'Estudios literarios: desde c. 2000',
        'Infantil/juvenil: antologías',
        'Infantil/juvenil, interés general: aventureros y forajidos',
        'Infantil/juvenil, interés general: brujas, magos y hechiceros',
        'Infantil/juvenil, interés general: humor y bromas',
        'Infantil/juvenil, interés general: misterios, lo sobrenatural',
        'Infantil/juvenil, interés general: reinas, reyes, princesas, príncipes, etc.',
        'Infantil/juvenil, interés general: textos teatrales',
        'Libros ilustrados: libros de personajes',
        'Mitos y leyendas / ficción mítica',
        'Narrativa de amor erótico',
        'Narrativa romántica histórica',
        'Narrativa romántica moderna y contemporánea',
        'Narrativa romántica con personajes de uniforme',
        'Narrativa romántica: amor puro',
        'Narrative theme: war and conflict',
        'Obras clásicas y anteriores al siglo xx',
        'Obras modernas y contemporáneas (desde 1900 en adelante)',
        'Realismo mágico',
        'Reseñas y guías de libros infantiles y juveniles',
        'Romantic comedies',
        'Seres legendarios y sobrenaturales, monstruos y criaturas',
        'Suspense romántico',
        'Tema narrativo: el amor y las relaciones',
        'Tema narrativo: exilio, migración, desarraigo',
        'Tema narrativo: identidad / sentido de pertenencia',
        'Tema narrativo: llegada a la madurez',
        'Tema narrativo: muerte, duelo, pérdida',
        'Tema narrativo: sentimiento del terruño',
        'Tema narrativo: viajes, travesías y desplazamientos',
        'Tragedias'
    ],
    'Política': [
        'Política y gobierno',
        'Tema narrativo: política',
        'Ideologías y movimientos políticos de extrema derecha',
        'Estructuras políticas: democracia',
        'Estructuras políticas: totalitarismo y dictadura',
        'Infantil/Juvenil, interés general: política y gobierno',
        'Conservadurismo e ideologías democráticas de centro derecha',
        'Liberalismo e ideologías democráticas de centro',
        'Infantil/Jugeníl, interés general: trabajo, política y sociedad',
        'Ideologías y movimientos políticos de extrema izquierda',
        'Socialismo e ideologías democráticas de centro izquierda',
        'Políticas del Gobierno central',
        'Geopolítica',
        'Política y protocolos medioambientales',
        'Anarquismo',
        'Opresión y persecución políticas',
        'Refugiados y asilo político',
        'Financiación y política científica',
        'Armas químicas y biológicas',
        'Líderes y liderazgo políticos',
        'Elecciones y referéndums / sufragios',
        'Políticas de gobiernos y administraciones regionales, autonómicos o locales',
        'Gobierno societario: función y responsabilidad del consejo de administración y de los directores',
        'Política verde / ecopolítica / ecologismo',
        'Diplomacia',
        'Grupos de presión, movimientos de protesta y de acción no violenta',
        'Grupos y movimientos revolucionarios',
        'Instituciones internacionales',
        'Nacionalismo',
        'Sistemas de bienestar y beneficios sociales',
        'Terrorismo, lucha armada'
    ],
    'Psicología': [
        'Mente, cuerpo y espíritu',
        'Mente, cuerpo y espíritu: pensamiento y práctica',
        'Emociones e inteligencia emocional',
        'Infantil / Juvenil, cuestiones personales y sociales: emociones, estados de ánimo, sentimientos y conductas',
        'Autoayuda, desarrollo personal y consejos prácticos',
        'Infantil / Juvenil, emociones: ira, enfado, frustración',
        'Psicología',
        'Psicología clínica',
        'Teoría psicoanalítica (psicología freudiana)',
        'Psicoterapia',
        'Psicología analítica y junguiana',
        'Mente, cuerpo y espíritu: meditación y visualización',
        'Hacer frente / asesorarse sobre los problemas del neurodesarrollo',
        'Habilidades emocionales («soft skills») y relaciones interpersonales',
        'Mindfulness. Atención o conciencia plena',
        'Psicología positiva',
        'Psicología humanista',
        'Psicología del deporte',
        'Psicofarmacología',
        'Infantil / Juvenil, emociones: tristeza, infelicidad, decepción',
        'Infantil / Juvenil, emociones: compasión, empatía, amabilidad',
        'Afirmación personal, motivación, autoestima y actitud mental positiva',
        'Crecimiento y desarrollo humanos',
        'Desarrollo personal y relaciones',
        'Estudios cognitivos',
        'Fortalecimiento de la memoria y técnicas del pensamiento',
        'Gestión del tiempo',
        'Hacer frente / asesorarse sobre la ansiedad y las fobias',
        'Hacer frente / asesorarse sobre la muerte y el duelo',
        'Hacer frente / asesorarse sobre la vejez',
        'Hacer frente / asesorarse sobre los problemas de drogas o alcohol',
        'Hacer frente / asesorarse sobre los problemas de la imagen corporal',
        'Hacer frente / asesorarse sobre los problemas de salud mental',
        'Hacer frente / asesorarse sobre los problemas del sueño',
        'Hacer frente / asesorarse sobre los trastornos alimentarios',
        'Hacer frente / asesorarse sobre los trastornos del sueño y su tratamiento',
        'Hacer frente / asesorarse sobre el estrés',
        'Infantil / juvenil, cuestiones personales y sociales: autoconocimiento y autoestima',
        'Neurociencias',
        'Neurología y neurofisiología clínicas',
        'Psiquiatría',
        'Teoría conductista (conductismo)',
        'Trastornos de la alimentación y su tratamiento',
        'Trastornos del sueño y su tratamiento',
        'Trastornos mentales y psiquiátricos'
    ],
    'Sociología': [
        'Sociedad y cultura: general',
        'Influencia de la ciencia y la tecnología sobre la sociedad',
        'Familia y salud',
        'Estudios de género, grupos de género',
        'Sociología de la familia y las relaciones sociales',
        'Violencia y abusos en la sociedad',
        'Animales y sociedad',
        'Infantil / Juvenil, cuestiones personales y sociales: relaciones (no familiares / grupos)',
        'Sociedad y ciencias sociales',
        'Primeros años: la familia',
        'Infantil / Juvenil, cuestiones personales y sociales: la familia y sus miembros',
        'Infantil / Juvenil, cuestiones personales y sociales: divorcio, separación y desmembración de la familia',
        'Población y demografía',
        'Medicina general y de familia',
        'Grupos sociales: grupos y comunidades religiosas',
        'Sociedades secretas',
        'Familia y relaciones: consejos y problemas',
        'Sociología del deporte y el ocio',
        'Sociología del trabajo y el esfuerzo',
        'Sociología de la muerte y el morir',
        'Estudios / temas sobre la comunidad LGBTQ+',
        'Instituciones y sociedades eruditas: general',
        'Grupos sociales: clubes y sociedades',
        'Sociología médica',
        'Control, privacidad y seguridad en la sociedad',
        'Gestión financiera de las sociedades',
        'Guías de viaje: vacaciones con niños, vacaciones familiares',
        'Actitudes sociales',
        'Asistencia social',
        'Bodas, planificadores de bodas',
        'Citas, relaciones, convivencia y matrimonio: consejos y problemas',
        'Clases sociales',
        'Consumismo',
        'Crímenes y delitos reales',
        'Crímenes y delitos reales: asesinos y homicidas en serie',
        'Crimen organizado',
        'Crimen, delito y misterio',
        'Cuidado y crianza de los niños: consejos para los padres',
        'Delincuentes',
        'Delitos con violencia',
        'Discriminación social y justicia social',
        'Embarazo, parto y cuidados del bebé',
        'Estudios de género',
        'Estudios étnicos',
        'Estudios regionales / internacionales',
        'Estudios sobre la paz y resolución de conflictos',
        'Estudios sobre el desarrollo',
        'Globalización',
        'Grupos por edades y generaciones',
        'Grupos sociales: estilos de vida alternativos',
        'Hacer frente / asesorarse sobre enfermedades y problemas de salud concretos',
        'Impacto social de las catástrofes / accidentes (naturales o provocados)',
        'Impacto social de los problemas medioambientales',
        'Infantil / juvenil, cuestiones personales y sociales: acoso escolar, violencia, maltrato y coacción de los compañeros',
        'Infantil / juvenil, cuestiones personales y sociales: discapacidad, disfunciones y necesidades especiales',
        'Infantil / juvenil, cuestiones personales y sociales: enfermedades y afecciones físicas concretas',
        'Infantil / juvenil, cuestiones personales y sociales: el cuerpo y la salud',
        'Infantil / juvenil, cuestiones personales y sociales: fuga, huida',
        'Infantil / juvenil, cuestiones personales y sociales: lgtbq+',
        'Infantil / juvenil, cuestiones personales y sociales: maltrato',
        'Infantil / juvenil, cuestiones personales y sociales: muerte y duelo',
        'Infantil / juvenil, cuestiones personales y sociales: multiculturalismo',
        'Infantil / juvenil, cuestiones personales y sociales: prejuicios e intolerancia',
        'Infantil / juvenil, cuestiones personales y sociales: racismo y antirracismo',
        'Infantil / juvenil, cuestiones personales y sociales: salud mental',
        'Infantil / juvenil, cuestiones personales y sociales: suicidio',
        'Infantil / juvenil, cuestiones sociales: asuntos ecológicos y del medioambiente',
        'Infantil / juvenil, temas sociales: asuntos de guerra y conflictos',
        'Infantil / juvenil, temas sociales: asuntos religiosos /debates',
        'Infantil / juvenil, temas sociales: migración y refugiados',
        'Infantil / juvenil: cuestiones y temas sociales',
        'Investigación social y estadística',
        'Investigación y detección de delitos',
        'Jubilación',
        'Migración, inmigración y emigración',
        'Nostalgia/añoranza: general',
        'Paternidad/maternidad: consejos y temas',
        'Pobreza y precariedad',
        'Prospectiva social, futurología',
        'Relación médico/paciente',
        'Relaciones intergeneracionales: consejos y dinámicas',
        'Relaciones: amigos / grupos de iguales',
        'Salud, enfermedad y adicción: aspectos sociales',
        'Separación y divorcio: consejos y temas',
        'Servicios sociales y bienestar, criminología',
        'Sexo y sexualidad: consejos y temas',
        'Sexo y sexualidad, aspectos sociales',
        'Small town communities / small town life',
        'Tecnologías digitales y de la información: aspectos éticos y sociales',
        'Tema narrativo: cuestiones medioambientales / el mundo natural',
        'Tema narrativo: cuestiones sociales',
        'Tema narrativo: diversidad, igualdad, inclusión',
        'Teoría social',
        'Teorías de la conspiración',
        'Cirugía estética',
        'Genética médica',
        'Aplicaciones industriales de investigación científica e innovación tecnológica'
    ]
}


ENCUADERNACION = {
    "Cartoné": "Cartoné",
    "Libro de cartón": "Cartoné",
    "Tapa blanda o Bolsillo": "Rústica",
    "Espiral": "Espiral",
    "Piel / Lujo": "Piel",
    "Libro": "Otro",
    "Audio": "Otro",
    "Archivo de audio descargable": "Otro",
    "Libro en otro formato": "Otro",
    "Producto multisoporte": "Otro",
    "Calendario": "Otro",
    "Agenda / Diario": "Otro",
    "No definida.": "Otro",
    None: None
}


# Los pesos de cada arquetipo deben sumar 1.0 para mantener la escala
PESOS_ARQUETIPO = {
    # Prioriza aparato crítico (notas, estudios) y la reputación/prestigio académico
    "estudio_investigacion": {
        "aparato_critico": 0.35,
        "prestigio": 0.35,
        "novedad": 0.15,
        "economico": 0.05,
        "formato_premium": 0.10
    },
    # Prioriza la novedad (últimas ediciones/traducciones) y el prestigio general
    "lectura_general": {
        "aparato_critico": 0.05,
        "prestigio": 0.35,
        "novedad": 0.40,
        "economico": 0.10,
        "formato_premium": 0.10
    },
    # Prioriza la presencia física (tapa dura, ediciones ilustradas) y el prestigio
    "coleccion_regalo": {
        "aparato_critico": 0.10,
        "prestigio": 0.25,
        "novedad": 0.10,
        "economico": 0.00,
        "formato_premium": 0.55
    },
    # Prioriza ediciones asequibles (precio bajo) y manejables (bolsillo/rústica)
    "escolar_juvenil": {
        "aparato_critico": 0.15,
        "prestigio": 0.20,
        "novedad": 0.10,
        "economico": 0.45,
        "formato_premium": 0.10
    }
}