TRADUCTOR_EDITOR = [
    "traduccion",
    "edicion_literaria",
    "edicion",
    "direccion_de_edicion",
    "edicion_y_traduccion",
]

OTROS_CONTRIBUIDORES = [
    "epilogo",
    "prologo",
    "trabajo_preliminar",
    "contribucion",
    "introduccion",
    "comentarios_a_la_traduccion",
    "introduccion_a_notas",
    "prefacio",
    "notas",
    "compilacion",
]

ILUSTRACIONES = [
    "ilustracion",
    "ilustracion_fotografica",
    "fotografia",
]

ESCOLARES = [
    "material_enseñanza",
    "tipo_material_enseñanza",
    "tipo_enseñanza",
    "asignatura",
    "ciclo",
]

CATEGORIAS = [
    "categorias",
    "pais_de_publicacion",
    "asignatura",
    "tipo_material_enseñanza",
    "ciclo",
]

COLUMNAS_FINALES = [
    "isbn",
    "ean",
    "titulo",
    "editorial",
    "id_editorial",
    "coleccion",
    "autoria",
    "traductor_y_editor",
    "otros_contribuidores",
    "subcategorias",
    "idioma_original",
    "idioma_de_publicacion",
    "fecha_publicacion",
    "n_paginas",
    "precio",
    "alto_mm",
    "ancho_mm",
    "grueso",
    "peso",
    "encuadernacion",
    "es_escolar",
    "es_ilustrado",
    "es_ibd",
    "sinopsis",
    "url",
    "img",
]


CATEGORIAS = [
    "Antropología",
    "Arqueología", 
    "Bellas Artes",
    "Biblioteconomía",
    "Comunicación",
    "Derecho",
    "Economía",
    "Educación",
    "Filosofía",
    "Geografía",
    "Historia",
    "Literatura",
    "Política",
    "Psicología",
    "Sociología"
]



SUBCATEGORIAS = {
    'Antropología': ['Sociología y antropología',
                    'Antropología social y cultural, etnografía',
                    'Antropología evolutiva / Evolución humana'],
    'Arqueología': ['Historia y arqueología', 'Arqueología', 'Yacimientos arqueológicos'],
    'Bellas Artes': ['Música',
                  'Ópera',
                  'Arquitectura',
                  'Artes',
                  'Arte musical, música orquestal y académica',
                  'Otras formas de arte gráfico o visual',
                  'Películas, cine',
                  'Escultura',
                  'Artes escénicas',
                  'Fotografía y fotógrafos',
                  'Biografía: arte y espectáculo',
                  'Pintura, técnica de pintura',
                  'Historia del arte',
                  'Figuras humanas representadas en el arte',
                  'Música popular',
                  'Artes: aspectos generales',
                  'Artistas, monografías sobre arte',
                  'Música sacra y religiosa',
                  'Fotografía: retratos y autorretratos',
                  'Moda y diseño de tejidos',
                  'Teoría del arte',
                  'Historia, teoría y crítica cinematográfica',
                  'Infantil/Juvenil, interés general: música y músicos',
                  'Libros y «packs» infantiles interactivos y de actividades: dibujar, colorear y '
                  'pintar',
                  'Infantil/Juvenil, interés general: artesanías',
                  'Músicas del mundo y estilos regionales',
                  'Música tradicional y folclórica',
                  'Fotografías: colecciones',
                  'Infantil/Juvenil, interés general: artes y artistas',
                  'Infantil/Juvenil, interés general: danza, «ballet»',
                  'Dibujo y dibujos',
                  'Cine: estilos y géneros',
                  'Artesanías, artes decorativas y manualidades',
                  'Artes decorativas',
                  'Desnudos representados en el arte',
                  'Conservación, restauración y cuidado de obras de arte',
                  'Fotografía: técnicas y principios específicos',
                  'Diseño gráfico',
                  'Directores de cine, productores',
                  'Arte religioso y ceremonial',
                  'Diseño de muebles',
                  'Guías y revistas de cine',
                  'Sectores del cine, la radio y la televisión',
                  'Música electrónica',
                  'Música coral',
                  'Urbanismo y urbanización: aspectos arquitectónicos',
                  'Retratos y autorretratos en el arte',
                  'Artes: técnicas y principios artísticos',
                  'Diseñadores individuales o grupos de diseño',
                  'Libros de cocina y restaurantes de cocineros famosos y de televisión',
                  'Ballet',
                  'Industria de la música',
                  'Cómics, viñetas y dibujos animados',
                  'Diseño de libros',
                  'Música de cine y espectáculos',
                  'Dirección y producción de teatro',
                  'Gestión de teatros',
                  'Teatro: técnicas y competencias básicas',
                  'Los animales en el arte',
                  'Realización y producción cinematográfica: conocimientos básicos y técnicos',
                  'Adulteración, falsificación y sustracción de obras de arte',
                  'Oficios, técnicas y artes tradicionales',
                  'Terapia creativa (por ejemplo, arte, música, teatro)',
                  'Sciences in medicine and healthcare',
                  'Cerámica, mosaicos y vidrio: obras de arte',
                  'Obras de arte textil',
                  'Internet y medios digitales: arte y actuación',
                  'Formas de arte no gráfico o digital',
                  'Arte: aspectos económicos',
                  'La naturaleza en el arte',
                  'Arte de la «performance»',
                  'Manuales de pintura, dibujo y arte',
                  'Arte digital, de los nuevos medios y videoarte',
                  'Grabados y estampación',
                  'Arquitectura: castillos y fortificaciones',
                  'Arquitectura: palacios, casas solariegas, mansiones',
                  'Enseñanza: música',
                  'Enseñanza: arte y diseño',
                  'Tecnología de los tintes, pigmentos y pinturas',
                  'Arte público',
                  'Fotoperiodismo y fotografía documental',
                  'Guiones y guionistas de cine',
                  'Ilustración y arte comercial',
                  'Diseño de productos',
                  'Géneros de cine, televisión o radio: histórico',
                  'Arquitectura y diseño respetuosos con el medioambiente («verde»)',
                  'Arquitectura: edificaciones domésticas de pequeñas dimensiones',
                  'Géneros de cine, televisión o radio: comedia y humor',
                  'Cine, televisión, radio y artes escénicas',
                  'Géneros de cine, televisión o radio: ciencia ficción, fantasía y terror',
                  'Géneros de cine, televisión o radio: drama',
                  'Equipos y técnicas de fotografía en general',
                  'Arte erótico',
                  'Metales preciosos, piedras preciosas y alhajas: obras de arte y diseño',
                  'Arte y pinturas murales',
                  'Guías de diseño de interiores, decoración y estilo',
                  'Arte botánico',
                  'Artes marciales',
                  'Diseño y planificación de jardines',
                  'Antigüedades, objetos de época y coleccionables: fotografías, grabados y mapas',
                  'Cine, televisión, radio y artes escénicas: obras de acompañamiento',
                  'Escenas de arte a pequeña escala seculares y domésticas',
                  'Enseñanza: teatro y artes escénicas',
                  'Infantil/Juvenil, interés general: dibujos animados y tebeos',
                  'Ficción infantil / Ficción juvenil: ópera espacial («space opera»)',
                  'Materiales en la arquitectura'],
    'Biblioteconomía': ['Bibliografías, catálogos',
                     'Bibliotecas y ciencias de la información/Museología'],
    'Comunicación': ['Lingüística e idiomas',
                  'Diccionarios',
                  'Reportajes, periodismo o colecciones de artículos periodísticos',
                  'Lingüística histórica y comparada',
                  'Infantil/Juvenil, interés general: televisión, vídeo y películas',
                  'Industria editorial y periodismo',
                  'Guías de redacción y corrección de textos',
                  'Comunicación y presentación empresarial',
                  'Humor relacionado con los medios de comunicación',
                  'Infantil/juvenil, cuestiones personales y sociales: drogas y adicciones',
                  'Diccionarios biográficos',
                  'Estudios de comunicación',
                  'Ingeniería de las comunicaciones/las telecomunicaciones',
                  'Adicciones y su tratamiento',
                  'Radio/pódcast',
                  'Bilingüismo y plurilingüismo',
                  'Publicidad',
                  'Televisión',
                  'Sociolingüística',
                  'Redes y comunicaciones informáticas',
                  'Diccionarios temáticos',
                  'Narrativa romántica: ricos, famosos, poderosos',
                  'Comunicación interpersonal y habilidades sociales',
                  'Hacer frente / asesorarse sobre las adicciones',
                  'Programación neurolingüística (PNL)',
                  'Televisión: estilos y géneros',
                  'Poderes psíquicos y fenómenos psíquicos',
                  'Gramática, sintaxis y morfología',
                  'Tesauros / Diccionarios de sinónimos',
                  'Diccionarios bilingües y multilingües',
                  'Semiótica/semiología',
                  'Guiones, obras e interpretaciones radiofónicos',
                  'Aprendizaje de idiomas: gramática, vocabulario y pronunciación',
                  'Lingüística computacional y de corpus',
                  'Conocimientos jurídicos: elaboración y redacción de textos jurídicos',
                  'Infantil / Juvenil, material de consulta: diccionarios y material de '
                  'referencia'],
    'Derecho': ['Derecho del deporte',
             'Derecho penal: delitos contra la persona',
             'Derecho de los animales',
             'Derechos civiles y ciudadanía',
             'Derecho constitucional y administrativo',
             'Derecho privado o civil: generalidades',
             'Derecho y procedimiento penal',
             'Derecho',
             'Metodología, teoría y filosofía del derecho',
             'Derecho: derechos humanos y libertades civiles',
             'Derecho del trabajo',
             'Derecho internacional marítimo',
             'Derecho internacional público: Espacios marinos y Derecho del mar',
             'Derecho mercantil',
             'Derecho comparado',
             'Derecho de familia',
             'Fuentes de derecho: legislación',
             'Constitución: Gobierno y Estado',
             'Derechos humanos, derechos civiles',
             'Historia del derecho',
             'Constitución',
             'Derecho tributario y arancelario',
             'Derecho inmobiliario / Derecho real, bienes inmuebles',
             'Adivinación mediante atributos físicos',
             'Derecho Internacional público: Derecho Económico Internacional e integración',
             'Derecho internacional público: Derecho Humanitario e intervención',
             'Ordenamientos jurídicos: procesos civiles, litigios y resolución de conflictos',
             'Contratación mercantil. Obligaciones y contratos',
             'Derecho internacional público: derechos humanos',
             'Derecho mercantil, de sociedades y de la competencia',
             'Derecho romano',
             'Ordenamientos jurídicos: general',
             'Derecho y sociedad: cuestiones relativas al género',
             'Derecho y sociedad: sociología del derecho',
             'Derecho de la libertad de información',
             'Proceso penal',
             'Derecho bursátil. Derecho de los mercados de capitales',
             'Derecho energético y de los recursos naturales',
             'Derecho internacional público: Derecho penal',
             'Derecho penal de menores',
             'Derecho de la justicia penal',
             'Derecho de la seguridad social y servicios asistenciales',
             'Derecho sanitario y de la seguridad pública',
             'Derecho médico y sanitario',
             'Derecho mercantil. Derecho financiero',
             'Profesión jurídica / práctica del derecho: general',
             'Ley islámica (Shariah)',
             'Derecho: guías de estudio y revisión',
             'Derecho de bienes. Derecho de propiedad',
             'Derecho sobre bienes personales',
             'Fuentes del derecho: jurisprudencia, precedentes',
             'Derecho de las personas mayores.'],
    'Economía': ['Economía y empresa',
              'Historia de la economía',
              'Negocios internacionales',
              'Banca',
              'Economía popular',
              'Economía internacional',
              'Economía agrícola y rural',
              'Economía regional / urbana',
              'Empresa y gestión',
              'Finanzas y sector financiero',
              'Economía política',
              'Contabilidad',
              'Microeconomía',
              'Propiedad y organización de empresas',
              'Empresas en manos de los trabajadores y cooperativas',
              'Economía del trabajo y la retribución',
              'Economía del bienestar',
              'Finanzas personales',
              'Economía del desarrollo y economías emergentes',
              'Emprendimiento y emprendedores / empresas emergentes / «startups»',
              'Estrategia empresarial',
              'Economía monetaria',
              'Ventas y marketing',
              'Economía de sectores específicos',
              'Macroeconomía',
              'Toma de decisiones en la gestión de empresas',
              'Innovación empresarial',
              'Biografía: negocios e industria',
              'Economía digital o de internet',
              'Enseñanza: estudios empresariales y economía',
              'Negociación empresarial',
              'Pequeñas empresas y trabajadores autónomos',
              'Contabilidad de gestión, teneduría de libros y auditoría',
              'Ética empresarial y responsabilidad social',
              'Economía conductista/conductual',
              'Delincuencia empresarial y de guante blanco',
              'Estudios empresariales: general',
              'Economía medioambiental',
              'Economía de la salud',
              'Banca y finanzas: guías de estudio y revisión',
              'Aprendizaje de idiomas para negocios, actividades profesionales y formación '
              'profesional',
              'Historia de empresas específicas/historia societaria',
              'Competencia empresarial'],
    'Educación': ['Educación multidisciplinar y cultura general',
               'Educación',
               'Libros de texto, manuales y material educativo',
               'Tradiciones filosóficas y escuelas de pensamiento',
               'Ficción infantil / Ficción juvenil: relatos sobre la escuela',
               'Enseñanza: matemáticas y cálculo',
               'Enseñanza: lengua materna/nativa',
               'Enseñanza: lengua, literatura y alfabetización',
               'Enseñanza: matemáticas, ciencia y tecnología, general',
               'Enseñanza: cuadernos de vacaciones',
               'Enseñanza: ciencias, general',
               'Enseñanza: tecnología',
               'Enseñanza: ciencias sociales, estudios sociales',
               'Enseñanza: estudios de religión',
               'Enseñanza y aprendizaje de lenguas',
               'Enseñanza: lenguas modernas (no maternas/nativas o segundas)',
               'Infantil / Juvenil, cuestiones personales y sociales: escuela, educación y '
               'profesores',
               'Salud personal y pública/educación para la salud',
               'Escuelas secundarias',
               'Escuelas primarias e intermedias',
               'Enseñanza de alumnos con discapacidades físicas',
               'Recursos y materiales didácticos para docentes',
               'Cuerpo docente / de educadores',
               'Sistemas de escritura, alfabetos',
               'Finalidad moral y social de la educación',
               'Enseñanza a estudiantes con dificultades de aprendizaje',
               'Consejos sobre la educación',
               'Infantil / Juvenil, cuestiones personales y sociales: educación sexual y '
               'realidades de la vida',
               'Educación/pedagogía progresista',
               'Enseñanza: ciencias de la familia y el consumidor/gestión doméstica',
               'Formación docente',
               'Enseñanza: historia',
               'Enseñanza: geografía',
               'Alfabetismo',
               'Enseñanza: otros tipos de formación profesional',
               'Enseñanza: educación física',
               'Enseñanza: estudios generales, destrezas y competencias educativas',
               'Enseñanza: formación profesional y otros temas',
               'Enseñanza a estudiantes con dificultades sociales, emocionales o conductuales',
               'Enseñanza: filosofía y ética',
               'Primeros años: el abecedario / el alfabeto',
               'Ciencia del deporte, educación física'],
    'Filosofía': ['Filosofía popular',
               'Filosofía ética y moral',
               'Filosofía social y política',
               'Filosofía popular: el sentido de la vida / encontrar el sentido a la vida',
               'Filosofía occidental desde 1800, aproximadamente',
               'Filosofía y religión',
               'Filosofía antigua griega y romana',
               'Biografía: filosofía y ciencias sociales',
               'Filosofía: metafísica y ontología',
               'Teoría y filosofía económicas',
               'Filosofía de la religión',
               'Filosofía: estética',
               'Filosofía: epistemología y teoría del conocimiento',
               'Filosofía occidental: Ilustración',
               'Infantil/Juvenil, interés general: criaturas sobrenaturales y mitológicas',
               'Ficción metafísica / filosófica',
               'Infantil/Juvenil, interés general: filosofía, religión y creencias',
               'Filosofía: lógica',
               'Filosofía de la ciencia',
               'Filosofía de la mente',
               'Medicina musculoesquelética',
               'Genética (no médica)',
               'Filosofía islámica y árabe',
               'Cibernética y teoría de sistemas',
               'La filosofía occidental en la Edad Media',
               'Bioética',
               'Lógica matemática',
               'Filosofía de Asia y de la India',
               'Ingeniería genética',
               'Filosofía del lenguaje',
               'Salud y seguridad en el puesto de trabajo',
               'Industrias químicas, biotecnológicas y farmacéuticas',
               'Filosofía humanista',
               'Temas de la filosofía',
               'Genética médica',
               'Ética médica y conducta profesional',
               'Armas químicas y biológicas',
               'Fonética, fonología',
               'Cirugía estética',
               'Infantil/Juvenil, interés general: filosofía',
               'Baloncesto',
               'Aplicaciones industriales de investigación científica e innovación tecnológica'],
    'Geografía': ['Comunidades rurales',
               'Ficción urbana',
               'Ficción infantil / Ficción juvenil: fantasía urbana contemporánea',
               'Atlas o mapas del mundo / regionales',
               'Mapas geográficos: especializados / temáticos',
               'Geografía humana',
               'Geografía regional',
               'Planificación y gestión urbana y municipal',
               'Geografía histórica',
               'Fantasía urbana',
               'Geografía de los asentamientos urbanos y rurales',
               'Comunidades urbanas',
               'Novela romántica: wésterns, rurales o campestres («outback»)',
               'Infantil/Juvenil, interés general: vida urbana',
               'Geografía del turismo',
               'Geografía política',
               'Cartografía, elaboración de mapas y proyecciones',
               'Cartas celestes y atlas astronómicos',
               'Geografía económica',
               'Mapas y atlas de viaje',
               'Subject atlases / Visual reference',
               'Geografía: obras de referencia',
               'Planificación y gestión rural',
               'Geografía del desarrollo y del medio ambiente',
               'Geografía física y topografía',
               'Cultivos urbanos/agricultura urbana',
               'Mapas de calles y planos de ciudades',
               'Mapas de viaje',
               'Atlas y mapas de carreteras',
               'Infantil / Juvenil, material de consulta: atlas y mapas',
               'Infantil/Juvenil, interés general: vida rural'],
    'Historia': ['Literatura: historia y crítica',
              'Cuentos, Historias cortas',
              'Historias marítimas',
              'Historia general y del mundo',
              'Historia social y cultural',
              'Historia de Europa',
              'Ficción: historias tradicionales, mitos y cuentos de hadas',
              'Historia de Asia',
              'Historia: acontecimientos y temas específicos',
              'Historias reales de guerra y combate',
              'Historia de Europa: Renacimiento',
              'Historia de la ciencia',
              'Historia marítima',
              'Historia militar',
              'Historia Antigua',
              'Jardines (descripciones, historia, etc.)',
              'Historia: teoría y métodos',
              'Historia de la religión',
              'Historias reales: general',
              'Historia de la medicina',
              'Ficción infantil / Ficción juvenil: historias de relaciones: relatos románticos, de '
              'amor o de amistad',
              'Ficción infantil / Ficción juvenil: terror, historias de fantasmas y de miedo',
              'Ficción infantil / Ficción juvenil: historias inspiradas en medios ajenos al libro '
              'o adaptadas a partir de ellos',
              'Ficción infantil / Ficción juvenil: historias de amistad',
              'Ficción infantil / Ficción juvenil: romances e historias de amor',
              'Ficción infantil / Ficción juvenil: aventuras e historias interactivas',
              'Infantil/Juvenil, interés general: historia y el pasado',
              'Historia del conocimiento (fundamentalmente para ciencias sociales y humanidades)',
              'Historias reales de supervivencia en abusos o injusticias',
              'Ficción infantil / Ficción juvenil: historias en verso',
              'Ficción infantil / Ficción juvenil: historias reales contadas como ficticias',
              'Ficción infantil / Ficción juvenil: ficción biográfica / historias autobiográficas',
              'Historia de América',
              'Novela gráfica, cómics o manga: memorias, historias reales y no ficción',
              'Terror contemporáneo e historias de fantasmas',
              'Historia de otras zonas y regiones geográficas',
              'Historiografía',
              'Lengua: historia y obras generales',
              'Historia de las matemáticas',
              'Historia de África',
              'Historia de Oriente Próximo',
              'Historia de Europa: Edad Media',
              'Historias reales de heroísmo, resistencia y supervivencia',
              'Confesiones e historias reales eróticas',
              'Historia de Australasia y del Pacífico',
              'Historia de la tecnología y la ingeniería',
              'Historia de Europa: romanos',
              'Historia de Europa: Reforma',
              'La Tierra: historia natural general. Interés general',
              'Ciencia ficción: historias de aventuras en el espacio',
              'Historia local',
              'Historia de Europa: vikingos',
              'Historia de América: período precolombino',
              'Historia del deporte',
              'Historias de superhéroes',
              'Historia familiar, genealogía',
              'Historia oral',
              'Historia de la industria y la industrialización',
              'Historias reales sobre descubrimientos, historia o ciencia',
              'Historia de África. período precolonial',
              'Historia: plagas, enfermedades, hambrunas, etc.',
              'Historias de vida animal',
              'Infantil/Juvenil, interés general: historias extraídas de textos sagrados o '
              'tradiciones religiosas',
              'Ficción infantil / Ficción juvenil: historias del calendario de Adviento'],
     'Literatura': ['Ficción moderna y contemporánea: general y literaria',
                'Biografía: escritores',
                'Ficción humorística',
                'Thriller/suspense',
                'Ficción especulativa',
                'Ficción',
                'Novelas sobre estilos de vida contemporáneos',
                'Literatura de viajes',
                'Biografía: general',
                'Novelas sobre la vida familiar',
                'Autobiografía: general',
                'Memorias',
                'Poesía',
                'Ficción biográfica / ficción autobiográfica',
                'Ficción: inspirada o adaptado a partir de soportes que no sean libros',
                'Biografías y estudios literarios',
                'Ficción histórica',
                'Fantasía',
                'Ficción clásica: general y literaria',
                'Colección de biografías',
                'Mitos y leyendas / Ficción mítica',
                'Ficción de terror y lo sobrenatural',
                'Fantasía romántica',
                'Biografía: ciencia, tecnología y medicina',
                'Novelas de sagas familiares/generacionales',
                'Fantasía contemporánea',
                'Ficción sobre distopías y utopías',
                'Ficción basada o inspirada en hechos reales',
                'Biografía: histórica, política y militar',
                'Literatura clásica de viajes',
                'Biografía: religiosa y espiritual',
                'Novelas de aventuras militares, de guerra y de combate',
                'Novelas clásicas policiacas y de misterio',
                'Ficción infantil / Ficción juvenil: fantasía negra («dark fantasy»)',
                'Ficción infantil / Ficción juvenil: fantasía romántica',
                'Ficción infantil/juvenil: relatos de humor',
                'Ficción infantil / Ficción juvenil: ficción de crimen y misterio',
                'Ficción infantil / Ficción juvenil: thrillers/suspense',
                'Ficción infantil / Ficción juvenil: fantasía',
                'Ficción infantil / Ficción juvenil: relatos de acción y aventuras',
                'Novela gráfica, cómic o manga: vida escolar o universitaria',
                'Ficción infantil / Ficción juvenil: realismo mágico, fantasía mágica',
                'Ficción infantil / Ficción juvenil: ficción clásica',
                'Ficción infantil / Ficción juvenil: general, moderna y contemporánea',
                'Ficción infantil / Ficción juvenil: ficción especulativa, distópica y utópica',
                'Ficción erótica',
                'Narrativa romántica oscura («dark romance»)',
                'Ficción infantil / Ficción juvenil: relatos sobre animales y naturaleza',
                'Ficción infantil / Ficción juvenil: relatos sobre la familia y el hogar',
                'Ficción satírica y paródica',
                'Crimen y misterio: novela negra',
                'Ficción infantil / Ficción juvenil: cuentos tradicionales',
                'Infantil/Juvenil, interés general: biografías y autobiografías',
                'Thriller/suspense: asesinos en serie',
                'Ficción infantil / Ficción juvenil: fantasía épica / fantasía heroica',
                'Ficción infantil/juvenil: relatos sobre deportes',
                'Ciencia ficción',
                'Ficción de género',
                'Ficción infantil / Ficción juvenil: ciencia ficción',
                'Ficción de aventuras/acción',
                'Novela histórica alternativa',
                'Suspense médico / Thriller médico',
                'Thriller psicológico',
                'Aventuras de ficción: Westerns',
                'Novela gráfica, cómic o manga: acción y aventura',
                'Thriller sobre asuntos políticos y legales',
                'Fantasía épica/fantasía heroica',
                'Biografía: deporte',
                'Libros ilustrados de cuentos',
                'Ciencia ficción: Militar',
                '«Technothriller», tecnosuspense',
                'Ficción religiosa y espiritual',
                'Infantil/Juvenil, interés general: literatura, libros y escritores',
                'Fantasía histórica',
                'Ficción infantil / Ficción juvenil: cuentos, relatos cortos',
                'Ciencia ficción: alienígenas/ovnis',
                'Ciencia ficción clásica',
                'Novela gráfica, cómic o manga: humorística',
                'Thriller sobre espías y espionaje',
                'Ficción deportiva',
                'Ficción traducida',
                'Infantil/Juvenil: poesía',
                'Ficción infantil / Ficción juvenil: ficción histórica',
                'Ficción infantil / Ficción juvenil: ejércitos y guerra',
                'Novela gráfica, cómic o manga: fantasía, esoterismo',
                'Novela gráfica, cómic o manga: romántica',
                'Ciencia ficción: viajes en el tiempo',
                'Ficción infantil / Ficción juvenil: fantasía histórica',
                'Ficción infantil / Ficción juvenil: «steampunk»',
                'Infantil / Juvenil, cuestiones personales y sociales: contactos, noviazgo, '
                'relaciones, romances y amor',
                'Ficción infantil / Ficción juvenil: fantasía mítica / ficción mítica',
                'Biografía: aventureros y exploradores',
                'Novela gráfica, cómic o manga: horror, sobrenatural',
                'Cómics de estilo o tradición estadouinidenses',
                'Novela gráfica, cómics o manga: adaptaciones literarias',
                'Cómics de tradición o estilo europeos',
                'Tiras de cómics',
                'Parodias y chanzas/bromas: no ficción',
                'Cuentos clásicos de terror y fantasmas',
                'Biografía: realeza',
                'Manuales de literatura, reseñas y guías de libros',
                'Fantasía cómica (humorística)',
                'Cómic y manga',
                'Novelas gráficas',
                'Literatura griega y romana antiguas',
                'Fantasía negra («dark fantasy»)',
                'Ficción epistolar',
                'Ciencia ficción: apocalíptica y posapocalíptica',
                'Ciencia ficción: futuro cercano',
                'Ciencia ficción: exploración espacial',
                'Thriller esotérico',
                'Romance: love triangles',
                'Romance: unlikely or unexpected lovers',
                'Romance: enemies to lovers',
                'Romance: cosy / cozy',
                'Romance: friends to lovers',
                'Romance: unintentional or forced proximity',
                'Romance: sports',
                'Romance: workplace',
                'Romance: fake or pretend relationships',
                'Narrativa romántica: fantasía y paranormal',
                'Suspense / Thriller: crimen organizado',
                'Romance: college / university',
                'Ficción infantil / Ficción juvenil: novela por entregas (folletines)',
                'Romance: bad boys / bad girls',
                'Cuentos populares y de hadas / Recreación de cuentos de hadas',
                'Ficción de lo oculto (ocultismo)',
                'Ciencia ficción: «steampunk»',
                'Novela corta',
                'Fantasmas y poltergeist',
                'Cómics de estilo manga o de tradición asiática oriental',
                'Novela gráfica, cómic o manga: superhéroes y supervillanos',
                'Novela gráfica, cómic o manga: ciencia ficción',
                'Novela gráfica, cómic o manga: crimen, misterio y suspense',
                'Cómics de estilo o tradición europeos',
                'Novela gráfica, cómic o manga: histórica',
                'Novela gráfica, cómic o manga: ficción o literatura modernas y contemporáneas',
                'Ficción: pastiche',
                'Novela gráfica / cómic: para adultos',
                'Biografía: medios sociales',
                'Formas de poesía: soneto',
                'Financial / Corporate thrillers',
                'Thriller/suspense: terrorismo'],
    'Política': ['Política y gobierno',
              'Tema narrativo: política',
              'Ideologías y movimientos políticos de extrema derecha',
              'Estructuras políticas: democracia',
              'Estructuras políticas: totalitarismo y dictadura',
              'Infantil/Juvenil, interés general: política y gobierno',
              'Conservadurismo e ideologías democráticas de centro derecha',
              'Liberalismo e ideologías democráticas de centro',
              'Infantil/Juvenil, interés general: trabajo, política y sociedad',
              'Ideologías y movimientos políticos de extrema izquierda',
              'Socialismo e ideologías democráticas de centro izquierda',
              'Políticas del Gobierno central',
              'Geopolítica',
              'Política y protocolos medioambientales',
              'Anarquismo',
              'Opresión y persecución políticas',
              'Refugiados y asilo político',
              'Financiación y política científica',
              'Líderes y liderazgo políticos',
              'Elecciones y referéndums / sufragios',
              'Políticas de gobiernos y administraciones regionales, autonómicos o locales',
              'Gobierno societario: función y responsabilidad del consejo de administración y de '
              'los directores',
              'Política verde / ecopolítica / ecologismo'],
    'Psicología': ['Mente, cuerpo y espíritu',
                'Mente, cuerpo y espíritu: pensamiento y práctica',
                'Emociones e inteligencia emocional',
                'Infantil / Juvenil, cuestiones personales y sociales: emociones, estados de '
                'ánimo, sentimientos y conductas',
                'Autoayuda, desarrollo personal y consejos prácticos',
                'Infantil / Juvenil, emociones: ira, enfado, frustración',
                'Psicología',
                'Psicología clínica',
                'Teoría psicoanalítica (psicología freudiana)',
                'Psicoterapia',
                'Psicología analítica y junguiana',
                'Mente, cuerpo y espíritu: meditación y visualización',
                'Hacer frente / asesorarse sobre los problemas del neurodesarrollo',
                'Habilidades emocionales («soft skills») y relaciones interpersonales',
                'Mindfulness. Atención o conciencia plena',
                'Psicología positiva',
                'Psicología humanista',
                'Psicología del deporte',
                'Psicofarmacología',
                'Infantil / Juvenil, emociones: tristeza, infelicidad, decepción',
                'Infantil / Juvenil, emociones: compasión, empatía, amabilidad'],
     'Sociología': ['Sociedad y cultura: general',
                'Influencia de la ciencia y la tecnología sobre la sociedad',
                'Familia y salud',
                'Estudios de género, grupos de género',
                'Sociología de la familia y las relaciones sociales',
                'Violencia y abusos en la sociedad',
                'Animales y sociedad',
                'Infantil / Juvenil, cuestiones personales y sociales: relaciones (no familiares / '
                'grupos)',
                'Sociedad y ciencias sociales',
                'Primeros años: la familia',
                'Infantil / Juvenil, cuestiones personales y sociales: la familia y sus miembros',
                'Infantil / Juvenil, cuestiones personales y sociales: divorcio, separación y '
                'desmembración de la familia',
                'Población y demografía',
                'Medicina general y de familia',
                'Grupos sociales: grupos y comunidades religiosas',
                'Sociedades secretas',
                'Familia y relaciones: consejos y problemas',
                'Sociología del deporte y el ocio',
                'Sociología del trabajo y el esfuerzo',
                'Sociología de la muerte y el morir',
                'Estudios / temas sobre la comunidad LGBTQ+',
                'Instituciones y sociedades eruditas: general',
                'Grupos sociales: clubes y sociedades',
                'Sociología médica',
                'Control, privacidad y seguridad en la sociedad',
                'Gestión financiera de las sociedades',
                'Guías de viaje: vacaciones con niños, vacaciones familiares']
}


ENCUADERNACION = {
    "Cartoné": "Cartoné",
    "Libro de cartón": "Cartoné",
    "Tapa blanda o Bolsillo": "Rústica",
    "Espiral": "Espiral",
    "Piel / Lujo": "Piel",
    "Libro": "Otro",
    "Audio": "Otro",
    "Archivo de audio descargable": "Otro",
    "Libro en otro formato": "Otro",
    "Producto multisoporte": "Otro",
    "Calendario": "Otro",
    "Agenda / Diario": "Otro",
    "No definida.": "Otro",
    None: None
}


SPI_A_ED = {
  "Planeta (Grupo 62. Grupo Planeta)": "Planeta",
  "Espasa (Grupo Planeta)": "Espasa",
  "Destino (Grupo Planeta)": "Destino",
  "Alfaguara": "Alfaguara",
  "Anagrama": "Editorial Anagrama",
  "Acantilado": "Acantilado",
  "Siruela": "Siruela",
  "Akal (Grupo Akal)": "Ediciones Akal",
  "Gredos (Grupo RBA)": "Gredos",
  "Alianza (Grupo Anaya, Hachette Livre)": "Alianza Editorial",
  "Alianza (Grupo Anaya / Hachette Livre)": "Alianza Editorial",
  "Cátedra (Grupo Anaya, Hachette Livre)": "Ediciones Cátedra",
  "Cátedra (Grupo Anaya / Hachette Livre)": "Ediciones Cátedra",
  "Real Academia Española (RAE)": "RAE",
  "Castalia": "Castalia Ediciones"
}